### ISSUE TITLE
Vlookup

### ISSUE THREAD

**Issue by AguilarTech** [mikeprivette/exceltricks#1]
Use of Vlookup can be replaced with Xlookup which already has a if not_found parameter built in.

**Comment by mikeprivette** [comment]
Interesting, I had not seen Xlookup before but it doesn't work in Google Sheets (yet).

**Comment by mikeprivette** [comment]
Added XLOOKUP as an alternative for Excel and left in the original formula that works with both Excel and Google Sheets. Thanks for submitting this!
